import { Budget, Transaction } from "../types";

export const mockTransactions: Transaction[] = [
  // --- February 2026 ---
  {
    id: "t-001",
    amount: 52000,
    category: "Salary",
    type: "income",
    date: "2026-02-01",
    note: "February salary",
    isRecurring: true,
  },
  {
    id: "t-002",
    amount: 12000,
    category: "Rent",
    type: "expense",
    date: "2026-02-02",
    note: "Monthly rent",
    isRecurring: true,
  },
  {
    id: "t-003",
    amount: 3200,
    category: "Food & Dining",
    type: "expense",
    date: "2026-02-05",
    note: "Groceries + Swiggy",
  },
  {
    id: "t-004",
    amount: 1400,
    category: "Transport",
    type: "expense",
    date: "2026-02-07",
    note: "Ola/Uber + metro",
  },
  {
    id: "t-005",
    amount: 4500,
    category: "Shopping",
    type: "expense",
    date: "2026-02-10",
    note: "Myntra sale haul",
  },
  {
    id: "t-006",
    amount: 800,
    category: "Utilities",
    type: "expense",
    date: "2026-02-12",
    note: "Electricity + internet",
  },
  {
    id: "t-007",
    amount: 1200,
    category: "Entertainment",
    type: "expense",
    date: "2026-02-14",
    note: "Valentine's dinner + movie",
  },
  {
    id: "t-008",
    amount: 8000,
    category: "Freelance",
    type: "income",
    date: "2026-02-18",
    note: "UI design project",
  },
  {
    id: "t-009",
    amount: 600,
    category: "Healthcare",
    type: "expense",
    date: "2026-02-20",
    note: "Pharmacy",
  },
  {
    id: "t-010",
    amount: 2000,
    category: "Investments",
    type: "expense",
    date: "2026-02-25",
    note: "SIP — Nifty 50 index",
    isRecurring: true,
  },

  // --- March 2026 ---
  {
    id: "t-011",
    amount: 52000,
    category: "Salary",
    type: "income",
    date: "2026-03-01",
    note: "March salary",
    isRecurring: true,
  },
  {
    id: "t-012",
    amount: 12000,
    category: "Rent",
    type: "expense",
    date: "2026-03-02",
    note: "Monthly rent",
    isRecurring: true,
  },
  {
    id: "t-013",
    amount: 2800,
    category: "Food & Dining",
    type: "expense",
    date: "2026-03-04",
    note: "Groceries",
  },
  {
    id: "t-014",
    amount: 1100,
    category: "Transport",
    type: "expense",
    date: "2026-03-08",
    note: "Cab + fuel",
  },
  {
    id: "t-015",
    amount: 6200,
    category: "Shopping",
    type: "expense",
    date: "2026-03-12",
    note: "Electronics — earbuds",
  },
  {
    id: "t-016",
    amount: 900,
    category: "Utilities",
    type: "expense",
    date: "2026-03-14",
    note: "Bills",
  },
  {
    id: "t-017",
    amount: 5000,
    category: "Freelance",
    type: "income",
    date: "2026-03-15",
    note: "Logo design",
  },
  {
    id: "t-018",
    amount: 2400,
    category: "Entertainment",
    type: "expense",
    date: "2026-03-20",
    note: "Holi weekend — outing",
  },
  {
    id: "t-019",
    amount: 1800,
    category: "Education",
    type: "expense",
    date: "2026-03-22",
    note: "Udemy courses",
  },
  {
    id: "t-020",
    amount: 2000,
    category: "Investments",
    type: "expense",
    date: "2026-03-25",
    note: "SIP",
    isRecurring: true,
  },
  {
    id: "t-021",
    amount: 3500,
    category: "Healthcare",
    type: "expense",
    date: "2026-03-28",
    note: "Doctor visit + tests",
  },

  // --- April 2026 ---
  {
    id: "t-022",
    amount: 52000,
    category: "Salary",
    type: "income",
    date: "2026-04-01",
    note: "April salary",
    isRecurring: true,
  },
  {
    id: "t-023",
    amount: 12000,
    category: "Rent",
    type: "expense",
    date: "2026-04-02",
    note: "Monthly rent",
    isRecurring: true,
  },
  {
    id: "t-024",
    amount: 3600,
    category: "Food & Dining",
    type: "expense",
    date: "2026-04-03",
    note: "Groceries + eating out",
  },
  {
    id: "t-025",
    amount: 1300,
    category: "Transport",
    type: "expense",
    date: "2026-04-06",
    note: "Monthly commute",
  },
  {
    id: "t-026",
    amount: 2200,
    category: "Shopping",
    type: "expense",
    date: "2026-04-09",
    note: "Summer clothes",
  },
  {
    id: "t-027",
    amount: 850,
    category: "Utilities",
    type: "expense",
    date: "2026-04-11",
    note: "Internet + electricity",
  },
  {
    id: "t-028",
    amount: 12000,
    category: "Freelance",
    type: "income",
    date: "2026-04-15",
    note: "Full website project",
  },
  {
    id: "t-029",
    amount: 1600,
    category: "Entertainment",
    type: "expense",
    date: "2026-04-18",
    note: "Concert tickets",
  },
  {
    id: "t-030",
    amount: 2000,
    category: "Investments",
    type: "expense",
    date: "2026-04-25",
    note: "SIP",
    isRecurring: true,
  },
];

export const mockBudgets: Budget[] = [
  { category: "Food & Dining", limit: 4000 },
  { category: "Transport", limit: 1500 },
  { category: "Shopping", limit: 5000 },
  { category: "Entertainment", limit: 2000 },
  { category: "Utilities", limit: 1200 },
  { category: "Healthcare", limit: 2000 },
  { category: "Education", limit: 3000 },
  { category: "Investments", limit: 5000 },
];
